name: today_and_tomorrow
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^7.9.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  injectable: ^2.3.5
  get_it: ^7.6.7
  intl: ^0.18.1
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  flutter_localizations:
    sdk: flutter
  reactive_forms: ^16.1.1
  gap: ^3.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  reactive_date_time_picker: ^3.0.0
  json_serializable: ^6.7.1
  objectbox: ^2.5.1
  path_provider: ^2.1.2
  objectbox_flutter_libs: any
  flutter_staggered_grid_view: ^0.7.0
  device_preview: ^1.1.0
  loading_overlay: ^0.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  injectable_generator: ^2.5.1
  auto_route_generator: ^7.3.2
  slang_build_runner: ^3.30.0
  flutter_lints: ^3.0.0
  objectbox_generator: any



objectbox:
  output_dir: infraestructure/core/objectbox

flutter:
  uses-material-design: true


  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          # weight: 400
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/Urbanist-Bold.ttf
          # weight: 700
        - asset: assets/fonts/Urbanist-Light.ttf
          # weitght: 100
        - asset: assets/fonts/Urbanist-Medium.ttf
          # weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          # weight: 500
    